config/routes.rb
Rails.application.routes.draw do
  resources :contacts do
    collection { post :import }
  end

  root to: "contacts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  require 'csv'

    validates :uid, presence: true, length: {minimum: 5, maximum: 5 }
    validates :phone, presence: true, length: {minimum: 10, maximum: 11}
    validates :first, presence: true, length: {minimum: 3, maximum: 55}
    validates :last, presence: true, length: {minimum: 2, maximum: 55}
    validates :email, presence: true, length: {minimum: 5, maximum: 320}

  def self.import(file_path)
    CSV.foreach(file_path, headers: true) do |row|
      contact_hash = row.to_hash
      contact = Contact.where(id: contact_hash["id"])

      if contact.count == 1
        # Prevent CSV updates from changing the database emails attribute
        contact.first.update_attributes(contact_hash.expect("email"))
      else
        Contact.create!(contact_hash)
      end
    end
  end

  def self.search(search)
    if search
      where('first LIKE ?', "%#{search}%")
    else
      where(nil)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    include ContactsHelper
    helper_method :sort_column, :sort_direction
  
    def index
      @contacts = Contact.search(contact_params[:search])
                         .order(sort_column + " " + sort_direction)
                         .paginate(:per_page => 3, :page => contact_params[:page])
    end
  
    def import
      
      begin
        file = contact_params[:file]
        file_path = file.path
        Contact.import(file_path)
        redirect_to root_url, notice: "Imported CSV file."
      rescue
        redirect_to root_url, notice: "Invalid CSV file format."
      end
    end
  
    private
  def sort_column
     Contact.column_defaults.include?(contact_params[:sort]) ? contact_params[:sort] : "first"
  end
  
    def sort_direction
      %w[asc desc].include?(contact_params[:direction]) ? contact_params[:direction] : "asc"
    end
  
    def contact_params
      params.permit(:uid, :phone, :first, :last, :email,
                    :file, :search, :page, :sort, :utf8,
                    :authenticity_token, :commit, :direction, :_)
      end
  end
  
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
    def sortable(column, title = nil)
        title ||= column.titleize
        css_class = column == self.sort_column ? "current #{self.sort_direction}" : nil
        direction = column == self.sort_column && self.sort_direction == "asc" ? "desc" : "asc"
        link_to title, request.parameters.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
      end
    
    
end

app/views/contacts/_contacts.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<table class="table table-sm table-bordered table-hover table-responsive pretty">
	<thead class="thead-default">
		<tr>
		    <th><%= sortable "number", "#"%></th>
		    <th><%= sortable "uid", "ID" %></th>
			<th><%= sortable "phone", "Phone" %></th>
			<th><%= sortable "first", "First" %></th>
			<th><%= sortable "last", "Last" %></th>
			<th><%= sortable "email", "Email" %></th>
		</tr>
	</thead>
	<% index = 0 %>
            <% @contacts.each do |contact| %>
    <% index += 1 %> 

		
     <tbody>
		<tr>
			<th scope="row"><%= index %></th>
		<!--#	<td class="text-primary"><%= contact.uid %></td> -->
			<td class="text-primary"><%= contact.uid %></td>
			<td class="text-primary"><%= contact.phone %></td>
			<td class="text-primary"><%= contact.first %></td>
			<td class="text-primary"><%= contact.last %></td>
			<td class="text-primary"><%= contact.email %></td>
			
		</tr>
	</tbody>
	<%end%>
</div>

<%= will_paginate @contacts %>

app/views/contacts/index.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8">
    <div class="contact-import">
      <h3>Upload and Import CSV Data</h3>
      <%= form_tag import_contacts_path, multipart: true do %>
          <%= file_field_tag :file, id: "choose-file", class: "btn btn-secondary btn-file" %>
          <%= submit_tag "Import CSV", id: "import-submit", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
  <div class="col-sm-12 col-md-4">
    <div class="contact-search">
      <%# content_for :title, "Contacts" %>
      <h3>Search</h3>
      <%= form_tag contacts_path, method: 'get', id: "contacts_search", class: "form-inline pull-xs-right" do %>
        <p>
          <%= text_field_tag :search, params[:search], placeholder: "", id: "search-input", class: "form-control" %>
          <%= submit_tag "Search", name: nil, id: "search-submit", class: "btn btn-success" %>
        </p>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="contact-list">
     <h3> Uploaded Contacts </h3>
      <div id="contacts">
      <%= render 'contacts' %></div>
    </div>
  </div>
</div>

app/views/contacts/index.js.erb
$("#contacts").html("<%= escape_javascript(render("contacts")) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || "Untitled" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head) %>
  </head>

  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
          <%#= debug name.inspect %>
          <% name = "info" if name == "notice" %>
          <%= content_tag :div, msg, class: "alert alert-#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) %>
      <%= yield %>
    </div>
  </body>
</html>